name: flutter_web_psychotest
description: Slisic Application.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  parse_server_sdk: ^1.0.24
  flutter:
    sdk: flutter

  # import responsive framework lybrary
  responsive_framework: ^0.0.14

  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

  flutter_webview_plugin: ^0.3.11

  # secure window manager
  flutter_windowmanager: ^0.0.2
  
  # zoom widget
  zoom_widget: ^0.1.3

  # device info
  device_info: ^2.0.0

  # liquid refresh
  liquid_pull_to_refresh: ^2.0.0

  # back button interceptor library
  back_button_interceptor: ^5.0.0
  
  # json table
  json_table: ^2.0.1

  # web dev
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_web_compilers: ^2.16.1
  # build_web_compilers: ^0.4.0

  shared_preferences: ^0.5.12+4

  # http
  http: ^0.12.2

  # smart select
  smart_select: ^4.3.2

  # search page
  search_page: ^1.4.0

  # auto search
  auto_search: ^1.0.6

  # Firebase library
  firebase: ^7.3.0
  # firebase_core: ^0.5.0
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_auth_web: ^0.3.2+3
  firebase_database: ^4.1.1
  # firebase messaging / push notification
  firebase_messaging: ^7.0.3

  font_awesome_flutter: ^8.4.0
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2

  # camera library
  camera: ^0.6.3+2
  path_provider: ^1.6.24
  path: ^1.7.0
  # image picker web
  flutter_web_image_picker: ^0.0.2
  image: ^2.1.19
  universal_html: ^1.2.3

  # dropdown library
  dropdownfield: ^1.0.3

  # provider library
  provider: ^4.3.2+1
  
  # get widget library
  getwidget: ^1.2.4
  
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.3

  # add graph fitur
  # https://pub.dev/packages/graphic
  graphic: ^0.3.0
  # https://pub.dev/packages/charts_flutter
  charts_flutter: ^0.9.0

  # email sender
  flutter_email_sender: ^4.0.0

  # mailto
  mailto: ^1.1.0

  # image picker
  image_picker: ^0.6.7+21

  # url launcher
  url_launcher: ^5.7.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  intl: ^0.16.1

  # import google fonts library
  google_fonts: ^1.1.0
  # import animations library
  animations: ^1.1.2
  # A flutter countdown timer
  flutter_countdown_timer: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # image assets
    - assets/images/Smart-black.png
    - assets/images/Smart-white.png
    - assets/images/human_initiative.png
    - assets/images/create_user_logo.png
    - assets/images/example_test_d.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ostrich
      fonts:
        - asset: assets/fonts/Ostrich/ostrich-regular.ttf
    # style: italic
    - family: Web
      fonts:
        - asset: assets/fonts/Web/webhostinghub-glyphs.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
